package com.example.tgbotdemo.domain.statemachine;

public enum ChatEvents {
    AUTH_APPROVED, AUTH_DECLINED, // From AUTH
    SHOW_USER_MONEY, SHOW_GUILD_MONEY, SHOW_ORDER_DIALOG, SHOW_ORDERS, SHOW_INFO_DIALOG, // From MAIN
    CELL_NOT_AVAILABLE, CELL_AVAILABLE, // From ORDER_ASKING_CELL
    RECORD_ORDER, WRONG_AMOUNT, // From ORDER_ASKING_AMOUNT
    SHOW_DELETE_DIALOG, // From ASKING_ACTION
    WRONG_ORDER_TO_DELETE, SUCCESSFULLY_DELETED, // From ASKING_TO_DELETE
    SHOW_INFO, // From INFO_ASKING_CELL
    BACK_TO_MENU // From any state
}
